/**
 * Hand-curated League of Legends champion dataset.
 *
 * Each entry in `CHAMPION_ROWS` is a pipe-delimited record with 11 fields and no
 * spaces around the pipes:
 *
 *   id|name|classes|damage|range|cc|engage|peel|waveclear|scaling|roles
 *
 *   id         Data Dragon key exactly as Riot uses it (e.g. `MonkeyKing` for
 *              Wukong, `Belveth`, `KSante`, `Chogath`, `FiddleSticks`). This is
 *              what keys into Riot's asset URLs, so it must match Riot exactly.
 *   name       Display name (`Wukong`, `K'Sante`, `Kai'Sa`).
 *   classes    Comma-separated, 1-2 of: tank, fighter, assassin, mage, marksman,
 *              enchanter, catcher. `catcher` = pick/hook supports (Blitzcrank,
 *              Thresh, Morgana); `enchanter` = buff/heal supports (Lulu, Janna,
 *              Soraka, Milio).
 *   damage     P = mostly physical, M = mostly magic, X = genuinely mixed.
 *   range      m = melee, r = ranged.
 *   cc         0-3, amount of reliable hard CC (stun/root/knockup/suppress).
 *              0 = essentially none (Master Yi, Katarina), 3 = loads (Leona).
 *   engage     0-3, ability to start a fight on the enemy's terms.
 *              Malphite/Leona = 3, Soraka/Sona = 0.
 *   peel       0-3, ability to protect a carry. Janna/Lulu/Braum = 3,
 *              Katarina = 0.
 *   waveclear  0-3, how fast the champion clears a wave once online.
 *              Anivia/Ziggs = 3, Udyr = 1.
 *   scaling    e = early-game power, m = mid, l = late-game hypercarry/scaler.
 *   roles      Comma-separated from top, jungle, mid, adc, support. Only the
 *              roles the champion is actually played in at a normal ranked
 *              level - usually 1-2, occasionally 3.
 *
 * The ratings (cc / engage / peel / waveclear / scaling) are judgement calls
 * curated by hand and kept internally consistent rather than derived from any
 * API. The identity fields (id, name, classes, damage, range) mirror Riot's
 * Data Dragon; on a machine with network access, `npm run refresh-champions`
 * can refresh those ddragon-derived fields against the live patch.
 *
 * Rows are sorted alphabetically (case-insensitive) by `id`.
 */

export const CHAMPION_ROWS: string[] = [
  'Aatrox|Aatrox|fighter|P|m|2|2|1|2|m|top',
  'Ahri|Ahri|mage|M|r|2|1|1|2|m|mid',
  'Akali|Akali|assassin|M|m|0|1|0|2|m|mid,top',
  'Akshan|Akshan|marksman,assassin|P|r|0|1|0|2|m|mid,top',
  'Alistar|Alistar|tank|M|m|3|3|3|0|e|support',
  'Ambessa|Ambessa|fighter|P|m|2|3|1|2|m|top,jungle',
  'Amumu|Amumu|tank|M|m|3|3|1|1|m|jungle,support',
  'Anivia|Anivia|mage|M|r|3|1|1|3|l|mid',
  'Annie|Annie|mage|M|r|3|2|1|2|e|mid,support',
  'Aphelios|Aphelios|marksman|P|r|1|0|1|2|l|adc',
  'Ashe|Ashe|marksman|P|r|3|2|1|2|m|adc,support',
  'AurelionSol|Aurelion Sol|mage|M|r|2|1|1|3|l|mid',
  'Aurora|Aurora|mage,assassin|M|r|2|2|1|2|m|mid,top',
  'Azir|Azir|mage,marksman|M|r|2|2|1|3|l|mid',
  'Bard|Bard|catcher,enchanter|M|r|3|2|2|1|m|support',
  'Belveth|Bel\'Veth|fighter|P|m|1|2|0|2|l|jungle',
  'Blitzcrank|Blitzcrank|catcher,tank|M|m|3|3|1|0|e|support',
  'Brand|Brand|mage|M|r|2|1|1|3|m|support,mid',
  'Braum|Braum|tank|M|m|3|2|3|0|e|support',
  'Briar|Briar|fighter,assassin|P|m|2|3|0|2|m|jungle',
  'Caitlyn|Caitlyn|marksman|P|r|1|0|1|2|l|adc',
  'Camille|Camille|fighter,assassin|X|m|2|2|1|1|m|top',
  'Cassiopeia|Cassiopeia|mage|M|r|2|0|1|2|l|mid',
  'Chogath|Cho\'Gath|tank,mage|M|m|3|1|2|2|l|top,mid',
  'Corki|Corki|marksman,mage|X|r|0|0|0|2|m|mid',
  'Darius|Darius|fighter|P|m|2|1|1|1|m|top',
  'Diana|Diana|assassin,fighter|M|m|2|3|1|2|m|jungle,mid',
  'Draven|Draven|marksman|P|r|1|0|1|1|m|adc',
  'DrMundo|Dr. Mundo|tank,fighter|X|m|1|1|1|2|l|top,jungle',
  'Ekko|Ekko|assassin|M|m|2|2|1|2|m|mid,jungle',
  'Elise|Elise|mage,assassin|M|m|2|2|0|1|e|jungle',
  'Evelynn|Evelynn|assassin|M|m|1|2|0|1|m|jungle',
  'Ezreal|Ezreal|marksman|X|r|0|0|0|2|l|adc',
  'FiddleSticks|Fiddlesticks|mage|M|r|3|3|1|3|m|jungle,support',
  'Fiora|Fiora|fighter,assassin|P|m|1|1|1|1|l|top',
  'Fizz|Fizz|assassin|M|m|2|2|0|1|m|mid',
  'Galio|Galio|tank,mage|M|m|3|3|2|2|m|mid,support',
  'Gangplank|Gangplank|fighter|X|m|1|1|1|3|l|top',
  'Garen|Garen|fighter,tank|P|m|1|1|1|2|m|top',
  'Gnar|Gnar|fighter,tank|X|r|3|3|1|2|m|top',
  'Gragas|Gragas|tank,mage|M|m|3|3|2|2|m|jungle,top',
  'Graves|Graves|marksman,fighter|P|r|1|1|0|2|m|jungle',
  'Gwen|Gwen|fighter,assassin|M|m|1|1|1|2|l|top,jungle',
  'Hecarim|Hecarim|fighter|P|m|2|3|1|2|m|jungle',
  'Heimerdinger|Heimerdinger|mage|M|r|2|1|1|3|m|mid,top,support',
  'Hwei|Hwei|mage|M|r|2|1|2|3|m|mid,support',
  'Illaoi|Illaoi|fighter|X|m|1|1|1|1|m|top',
  'Irelia|Irelia|fighter,assassin|P|m|2|2|1|2|l|top,mid',
  'Ivern|Ivern|enchanter|M|r|2|1|3|1|m|jungle',
  'Janna|Janna|enchanter|M|r|2|0|3|1|m|support',
  'JarvanIV|Jarvan IV|fighter,tank|P|m|3|3|2|1|m|jungle',
  'Jax|Jax|fighter,assassin|X|m|2|1|1|1|l|top,jungle',
  'Jayce|Jayce|fighter,marksman|P|r|1|1|1|2|m|top,mid',
  'Jhin|Jhin|marksman|P|r|2|1|1|2|m|adc',
  'Jinx|Jinx|marksman|P|r|1|0|0|3|l|adc',
  'Kaisa|Kai\'Sa|marksman,assassin|X|r|0|1|0|2|l|adc',
  'Kalista|Kalista|marksman|P|r|2|1|1|1|m|adc',
  'Karma|Karma|mage,enchanter|M|r|2|1|3|2|m|support,mid',
  'Karthus|Karthus|mage|M|r|1|0|1|3|l|jungle,mid',
  'Kassadin|Kassadin|assassin,mage|M|m|1|1|1|2|l|mid',
  'Katarina|Katarina|assassin|X|m|0|1|0|2|m|mid',
  'Kayle|Kayle|marksman,mage|X|r|1|0|2|2|l|top,mid',
  'Kayn|Kayn|assassin,fighter|X|m|2|2|0|1|m|jungle',
  'Kennen|Kennen|mage|M|r|3|2|1|2|m|top',
  'Khazix|Kha\'Zix|assassin|P|m|1|1|0|1|m|jungle',
  'Kindred|Kindred|marksman|P|r|1|0|1|2|l|jungle',
  'Kled|Kled|fighter|P|m|2|3|1|1|e|top',
  'KogMaw|Kog\'Maw|marksman|X|r|1|0|0|2|l|adc',
  'KSante|K\'Sante|tank,fighter|X|m|3|2|2|1|m|top',
  'Leblanc|LeBlanc|assassin,mage|M|r|1|1|0|1|m|mid',
  'LeeSin|Lee Sin|fighter,assassin|P|m|2|3|1|1|e|jungle',
  'Leona|Leona|tank|M|m|3|3|2|0|e|support',
  'Lillia|Lillia|fighter,mage|M|m|2|2|1|3|m|jungle',
  'Lissandra|Lissandra|mage|M|r|3|3|2|2|m|mid',
  'Lucian|Lucian|marksman|P|r|0|0|0|2|m|adc,mid',
  'Lulu|Lulu|enchanter|M|r|2|0|3|1|m|support',
  'Lux|Lux|mage|M|r|3|1|2|2|m|mid,support',
  'Malphite|Malphite|tank|M|m|3|3|2|1|m|top,support',
  'Malzahar|Malzahar|mage|M|r|3|1|1|3|m|mid',
  'Maokai|Maokai|tank|M|m|3|3|2|2|m|support,jungle,top',
  'MasterYi|Master Yi|assassin,fighter|P|m|0|1|0|2|l|jungle',
  'Mel|Mel|mage|M|r|2|1|2|2|m|mid,support',
  'Milio|Milio|enchanter|M|r|1|0|3|1|m|support',
  'MissFortune|Miss Fortune|marksman|P|r|1|0|1|3|m|adc',
  'MonkeyKing|Wukong|fighter|P|m|2|3|1|2|m|top,jungle',
  'Mordekaiser|Mordekaiser|fighter,mage|M|m|2|1|1|2|l|top',
  'Morgana|Morgana|catcher,mage|M|r|3|1|2|2|m|support,mid',
  'Naafiri|Naafiri|assassin|P|m|1|2|0|1|m|mid,jungle',
  'Nami|Nami|enchanter|M|r|2|1|3|1|m|support',
  'Nasus|Nasus|fighter,tank|X|m|2|1|1|2|l|top',
  'Nautilus|Nautilus|tank,catcher|M|m|3|3|2|1|e|support,jungle',
  'Neeko|Neeko|mage|M|r|3|2|1|2|m|mid,support',
  'Nidalee|Nidalee|assassin,mage|M|r|1|1|1|1|e|jungle',
  'Nilah|Nilah|marksman,fighter|P|m|2|1|2|2|l|adc',
  'Nocturne|Nocturne|assassin,fighter|P|m|2|3|0|1|m|jungle',
  'Nunu|Nunu & Willump|tank,mage|M|m|3|3|1|2|m|jungle',
  'Olaf|Olaf|fighter|P|m|1|2|1|1|e|top,jungle',
  'Orianna|Orianna|mage|M|r|3|1|2|3|l|mid',
  'Ornn|Ornn|tank|X|m|3|3|2|1|l|top',
  'Pantheon|Pantheon|fighter,assassin|P|m|2|3|1|1|e|top,mid,support',
  'Poppy|Poppy|tank,fighter|P|m|3|2|3|1|m|jungle,top,support',
  'Pyke|Pyke|assassin,catcher|P|m|3|3|1|1|m|support',
  'Qiyana|Qiyana|assassin|P|m|2|2|0|1|m|mid',
  'Quinn|Quinn|marksman,assassin|P|r|1|1|1|1|e|top',
  'Rakan|Rakan|catcher,enchanter|M|m|3|3|2|0|m|support',
  'Rammus|Rammus|tank|M|m|3|2|1|1|m|jungle',
  'RekSai|Rek\'Sai|fighter,assassin|P|m|2|3|0|1|e|jungle',
  'Rell|Rell|tank,catcher|M|m|3|3|2|0|m|support',
  'Renata|Renata Glasc|catcher,enchanter|M|r|3|1|3|1|m|support',
  'Renekton|Renekton|fighter|P|m|2|2|1|2|e|top',
  'Rengar|Rengar|assassin|P|m|1|2|0|1|m|jungle,top',
  'Riven|Riven|fighter,assassin|P|m|2|2|1|2|m|top',
  'Rumble|Rumble|fighter,mage|M|m|2|1|1|3|m|top,mid',
  'Ryze|Ryze|mage|M|r|2|1|1|3|l|mid',
  'Samira|Samira|marksman,assassin|P|r|1|1|0|2|l|adc',
  'Sejuani|Sejuani|tank|M|m|3|3|2|1|m|jungle',
  'Senna|Senna|marksman,enchanter|P|r|2|1|3|1|l|support,adc',
  'Seraphine|Seraphine|enchanter,mage|M|r|3|1|3|3|m|support,mid',
  'Sett|Sett|fighter,tank|X|m|3|2|2|1|m|top,support',
  'Shaco|Shaco|assassin|X|m|1|1|0|1|m|jungle,support',
  'Shen|Shen|tank|M|m|2|2|3|1|m|top,support',
  'Shyvana|Shyvana|fighter|X|m|1|2|0|2|l|jungle',
  'Singed|Singed|tank,fighter|M|m|2|1|1|2|m|top',
  'Sion|Sion|tank|X|m|3|3|2|2|l|top',
  'Sivir|Sivir|marksman|P|r|0|0|1|3|m|adc',
  'Skarner|Skarner|tank,fighter|X|m|3|3|1|1|m|jungle,top',
  'Smolder|Smolder|marksman|X|r|1|0|0|2|l|adc',
  'Sona|Sona|enchanter|M|r|1|0|3|2|l|support',
  'Soraka|Soraka|enchanter|M|r|1|0|3|1|m|support',
  'Swain|Swain|mage,tank|M|r|3|2|1|2|m|mid,support',
  'Sylas|Sylas|assassin,mage|M|m|2|2|1|2|m|mid,top',
  'Syndra|Syndra|mage|M|r|3|1|2|2|l|mid',
  'TahmKench|Tahm Kench|tank|M|m|3|1|3|1|m|top,support',
  'Taliyah|Taliyah|mage|M|r|3|1|2|3|m|jungle,mid',
  'Talon|Talon|assassin|P|m|1|1|0|2|m|mid,jungle',
  'Taric|Taric|enchanter,tank|M|m|2|1|3|1|m|support',
  'Teemo|Teemo|marksman,mage|M|r|2|0|1|2|m|top,jungle',
  'Thresh|Thresh|catcher,tank|M|m|3|3|3|0|m|support',
  'Tristana|Tristana|marksman|P|r|2|1|1|2|l|adc,mid',
  'Trundle|Trundle|fighter,tank|P|m|2|2|2|1|m|jungle,top',
  'Tryndamere|Tryndamere|fighter,assassin|P|m|1|1|0|1|l|top',
  'TwistedFate|Twisted Fate|mage|X|r|2|1|1|3|m|mid',
  'Twitch|Twitch|marksman,assassin|P|r|1|0|0|2|l|adc',
  'Udyr|Udyr|fighter,tank|X|m|2|2|1|1|m|jungle',
  'Urgot|Urgot|fighter,marksman|P|r|3|1|1|2|m|top',
  'Varus|Varus|marksman,mage|X|r|3|1|1|2|m|adc',
  'Vayne|Vayne|marksman,assassin|P|r|2|0|1|0|l|adc,top',
  'Veigar|Veigar|mage|M|r|3|1|1|3|l|mid,support',
  'Velkoz|Vel\'Koz|mage|M|r|2|0|1|3|m|mid,support',
  'Vex|Vex|mage|M|r|2|2|1|2|m|mid',
  'Vi|Vi|fighter,assassin|P|m|3|3|1|1|m|jungle',
  'Viego|Viego|assassin,fighter|P|m|2|2|0|1|l|jungle',
  'Viktor|Viktor|mage|M|r|2|1|1|3|l|mid',
  'Vladimir|Vladimir|mage|M|r|0|0|1|2|l|mid,top',
  'Volibear|Volibear|fighter,tank|X|m|3|3|1|2|m|jungle,top',
  'Warwick|Warwick|fighter,tank|X|m|3|3|1|1|e|jungle,top',
  'Xayah|Xayah|marksman|P|r|2|0|1|2|l|adc',
  'Xerath|Xerath|mage|M|r|2|0|1|3|m|mid,support',
  'XinZhao|Xin Zhao|fighter,assassin|P|m|3|3|1|1|e|jungle',
  'Yasuo|Yasuo|fighter,assassin|P|m|2|1|1|2|l|mid,top',
  'Yone|Yone|assassin,fighter|X|m|2|2|1|2|l|mid,top',
  'Yorick|Yorick|fighter|P|m|2|1|1|2|l|top',
  'Yunara|Yunara|marksman|X|r|0|0|0|2|l|adc',
  'Yuumi|Yuumi|enchanter|M|r|1|0|3|1|l|support',
  'Zac|Zac|tank|M|m|3|3|2|2|m|jungle',
  'Zed|Zed|assassin|P|m|1|1|0|2|m|mid',
  'Zeri|Zeri|marksman|X|r|1|0|1|2|l|adc',
  'Ziggs|Ziggs|mage|M|r|1|0|1|3|m|mid,adc',
  'Zilean|Zilean|enchanter,mage|M|r|3|1|3|2|m|support,mid',
  'Zoe|Zoe|mage|M|r|3|0|1|2|m|mid',
  'Zyra|Zyra|mage,catcher|M|r|3|1|2|3|m|support',
];
